# kafka-kraft docker-compose.yml
version: '3.8'
networks:
  kafka-network:
    driver: bridge
services:
  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:7.6.0
    platform: linux/arm64
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka-1:/var/lib/kafka/data
    networks:
      - kafka-network
    environment:
      # kafka 클러스터로 묶일 클러스터 ID
      CLUSTER_ID: aj-n6qXnQZqWSWsZP92ybA
      # kafka node 식별자 (required for KRaft mode)
      KAFKA_NODE_ID: 1
      # kafka 서버의 역할 controller, broker, controller,broker(동시) (required for KRaft mode)
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # zookeeper.connect와 대응하는 역할을 기지고 있으며, Controller Quorum에 연결할 수 있는 노드를 식별한다. (required for KRaft mode)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      # Kraft mode 사용 시 여러 브로커 중 하나가 컨트롤러 역할을 하는데 이 노드가 다른 브로커와 통신할 때 사용할 리스너를 지정, zookeeper 모드에서는 설정하면 안됨. (required for KRaft mode)
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # kafka 내부 통신용 리스너 설정.
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # 리스너 별로 사용할 보안 프로토콜의 키/값 쌍.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # 리스너 설정(acvertised listener: 클라이언트에게 알려줄 주소, listener: 클라이언트가 접속할 수 있는 주소)
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENERS: INTERNAL://kafka-1:9094,CONTROLLER://kafka-1:9093,EXTERNAL://0.0.0.0:9092
  kafka-2:
    container_name: kafka-2
    image: confluentinc/cp-kafka:7.6.0
    platform: linux/arm64
    ports:
      - 9093:9092
    volumes:
      - ./data/kafka-2:/var/lib/kafka/data
    networks:
      - kafka-network
    environment:
      CLUSTER_ID: aj-n6qXnQZqWSWsZP92ybA
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENERS: INTERNAL://kafka-2:9094,CONTROLLER://kafka-2:9093,EXTERNAL://0.0.0.0:9092
  kafka-3:
    container_name: kafka-3
    image: confluentinc/cp-kafka:7.6.0
    platform: linux/arm64
    ports:
      - 9094:9092
    volumes:
      - ./data/kafka-3:/var/lib/kafka/data
    networks:
      - kafka-network
    environment:
      CLUSTER_ID: aj-n6qXnQZqWSWsZP92ybA
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENERS: INTERNAL://kafka-3:9094,CONTROLLER://kafka-3:9093,EXTERNAL://0.0.0.0:9092
  kafka-ui:
    image: provectuslabs/kafka-ui:master
    platform: linux/arm64
    container_name: kafka-ui
    ports:
      - "9090:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-kraft-cluster
      # kafka 내부 통신용 port 사용
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9094,kafka-2:9094,kafka-3:9094
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - kafka-network
